[project]
name = "fastapi-learn"
version = "0.1.0"
description = "Fastapi practice"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "fastapi>=0.116.1",
    "uvicorn[standard]>=0.35.0",
]
